### ISSUE TITLE
Review project information

### ISSUE THREAD

**Issue by danielfdsilva** [AMT-Autoridade/amt#3]
Review the project information in the README and package.json

**Comment by leihla** [comment]
@danielfdsilva não te esqueças de tirar as referências à development seed dos ficheiros

**Comment by danielfdsilva** [comment]
@leihla Acho que já não há nenhuma referência. Agora tens de atualizar os ficheiros com o que achares pertinente. incluindo uma descrição para o README.

**Comment by leihla** [comment]
Ai mãe.
